 
var incapGetObjectActionMapping = {
	// must map all params here as a list below as follows:
	// "site_id":{"name":"site_id","type":"list","values":[]},
	"site_id":{"action":"/api/prov/v1/sites/list","listName":"sites","id":"site_id","displayText":"domain","isParent":true,"children":["dc_id"]},
	"dc_id":{"action":"/api/prov/v1/sites/dataCenters/list","listName":"DCs","id":"id","displayText":"name","parents":["site_id"]}/*,
	"rule_id":{"action":"/api/prov/v1/sites/dataCenters/list","listName":"DCs","id":"id","displayText":"name"},
	"config_id":{"name":"config_id","type":"string","values":""},
	"dc_id":{"name":"dc_id","type":"string","values":""},
	"logs_account_id":{"name":"logs_account_id","type":"int","values":""},
	"parent_id":{"name":"parent_id","type":"int","values":""},
	"plan_id":{"name":"plan_id","type":"string","values":""},
	"ref_id":{"name":"ref_id","type":"string","values":""},*/
}

var incapCopyObjectURLMappings = {
	"incap_rules":{"displayText":"Incap Rules","action":"/api/prov/v1/sites/incapRules/add","type":"incap_rules"},
	"ADR_Forward":{"displayText":"ADR Forward","action":"/api/prov/v1/sites/incapRules/add","type":"incap_rules"},
	"ADR_Redirect":{"displayText":"ADR Redirect","action":"/api/prov/v1/sites/incapRules/add","type":"incap_rules"},
	"ADR_Rewrite":{"displayText":"ADR Rewrite","action":"/api/prov/v1/sites/incapRules/add","type":"incap_rules"},
	"Forward":{"displayText":"ADR Forward","action":"/api/prov/v1/sites/incapRules/add","type":"incap_rules"},
	"Redirect":{"displayText":"ADR Redirect","action":"/api/prov/v1/sites/incapRules/add","type":"incap_rules"},
	"Rewrite":{"displayText":"ADR Rewrite","action":"/api/prov/v1/sites/incapRules/add","type":"incap_rules"},
	"login_protect":{"displayText":"Login Protect","action":"/api/prov/v1/sites/lp/configure"},
	"acls":{"displayText":"ACLs","action":"/api/prov/v1/sites/configure/acl","type":"acl"},
	"api.acl.blacklisted_countries":{"displayText":"Visitors from blacklisted Countries","action":"/api/prov/v1/sites/configure/acl","type":"Security/ACL"},
	"api.acl.blacklisted_ips":{"displayText":"Visitors from blacklisted IPs","action":"/api/prov/v1/sites/configure/acl","type":"Security/ACL"},
	"api.acl.whitelisted_ips":{"displayText":"Visitors from whitelisted IPs","action":"/api/prov/v1/sites/configure/acl","type":"Security/ACL"},
	"api.acl.blacklisted_urls":{"displayText":"Visitors from blacklisted URLs","action":"/api/prov/v1/sites/configure/acl","type":"Security/ACL"},
	"api.threats.backdoor":{"displayText":"Backdoor Protect","action":"/api/prov/v1/sites/configure/security","type":"WAF"},
	"api.threats.bot_access_control":{"displayText":"Bot Access Control","action":"/api/prov/v1/sites/configure/security","type":"WAF"},
	"api.threats.cross_site_scripting":{"displayText":"Cross Site Scripting","action":"/api/prov/v1/sites/configure/security","type":"WAF"},
	"api.threats.ddos":{"displayText":"DDOS","action":"/api/prov/v1/sites/configure/security","type":"WAF"},
	"api.threats.illegal_resource_access":{"displayText":"Illegal Resource Access","action":"/api/prov/v1/sites/configure/security","type":"WAF"},
	"api.threats.remote_file_inclusion":{"displayText":"Remote File Inclusion","action":"/api/prov/v1/sites/configure/security","type":"WAF"},
	"api.threats.sql_injection":{"displayText":"SQL Injection","action":"/api/prov/v1/sites/configure/security","type":"WAF"}
	//"dns":{"displayText":"DNS","action":""},
	/*"ips":{"displayText":"IPs","action":""}
	"original_dns":{"displayText":"IPs","action":""},
	"performance_configuration":{"displayText":"IPs","action":""},
	"res":{"displayText":"IPs","action":""},
	"sealLocation":{"displayText":"IPs","action":""},
	"security":{"displayText":"IPs","action":""},
	"siteDualFactorSettings":{"displayText":"IPs","action":""},
	"ssl":{"displayText":"IPs","action":""},
	"warnings":{"displayText":"IPs","action":""},*/
}

var defaultRuleConfigMapping = {
	"api.acl.blacklisted_countries":{ "rule_id":"api.acl.blacklisted_countries" },
	"api.acl.blacklisted_ips":{ "rule_id":"api.acl.blacklisted_ips" },
	"api.acl.whitelisted_ips":{ "rule_id":"api.acl.whitelisted_ips" },
	"api.acl.blacklisted_urls":{ "rule_id":"api.acl.blacklisted_urls" },
	"api.threats.backdoor":{ "rule_id":"api.threats.backdoor","action":"api.threats.action.quarantine_url" },
	"api.threats.bot_access_control":{ "rule_id":"api.threats.bot_access_control","action":"api.threats.action.block_request" },
	"api.threats.cross_site_scripting":{ "rule_id":"api.threats.cross_site_scripting","action":"api.threats.action.block_request" },
	"api.threats.ddos":{ 
		"rule_id":"api.threats.ddos",
		"action":"api.threats.action.block_request",
		"ddos_traffic_threshold":1000,
		"activation_mode":"api.threats.ddos.activation_mode.auto"
	},
	"api.threats.illegal_resource_access":{ "rule_id":"api.threats.illegal_resource_access","action":"api.threats.action.alert" },
	"api.threats.remote_file_inclusion":{ "rule_id":"api.threats.remote_file_inclusion","action":"api.threats.action.block_request" },
	"api.threats.sql_injection":{ "rule_id":"api.threats.sql_injection","action":"api.threats.action.alert" }	
}

var ACLWAFRuleNameMapping = {
	"Security Rules":{
		"api.acl.blacklisted_countries":"Visitors from blacklisted Countries",
		"api.acl.blacklisted_ips":"Visitors from blacklisted IPs",
		"api.acl.whitelisted_ips":"Visitors from whitelisted IPs",
		"api.acl.blacklisted_urls":"Visitors from blacklisted URLs"
	},
	"WAF Rules":{
		"api.threats.backdoor":"Backdoor Protect",
		"api.threats.bot_access_control":"Bot Access Control",
		"api.threats.cross_site_scripting":"Cross Site Scripting (XSS)",
		"api.threats.ddos":"DDoS",
		"api.threats.illegal_resource_access":"Illegal Resource Access",
		"api.threats.remote_file_inclusion":"Remote File Inclusion",
		"api.threats.sql_injection":"SQL Injection"
	}
}
// Use jsonParamMapping to override or hardcode param values/objects in the event they are not parsed from the WADL/XSD correctly
// obj, array (any structure of nested objects), list (hard-coded set of values displayed in dropdown),listPair {"displayText":"","val":""} multi, string, boolean, int, filter (special case for filter paramater)
var incapJsonParamMapping = {	
	"extSiteId":{"desc":"Numeric identifier of the account to operate on",
		"type":"string","values":"48295835"},
	"allow_caching":{"desc":"",
		"type":"list","values":["","true","false"]},
	"access_key":{"desc":"S3 access key.",
		"type":"string","values":""},
	"account_id":{"desc":"Numeric identifier of the account to operate on",
		"type":"int","values":""},
	"account_name":{"desc":"Account Name",
		"type":"string","values":""},
	"action":{"desc":"",
		"type":"listPair","values":[
			{"displayText":"Redirect (ADR)","val":"RULE_ACTION_REDIRECT"},
			{"displayText":"Rewrite URL (ADR)","val":"RULE_ACTION_REWRITE_URL"},
			{"displayText":"Rewrite Header (ADR)","val":"RULE_ACTION_REWRITE_HEADER"},
			{"displayText":"Rewrite Cookie (ADR)","val":"RULE_ACTION_REWRITE_COOKIE"},
			{"displayText":"Delete Header (ADR)","val":"RULE_ACTION_DELETE_HEADER"},
			{"displayText":"Delete Cookie (ADR)","val":"RULE_ACTION_DELETE_COOKIE"},
			{"displayText":"Forward to Data Center (ADR)","val":"RULE_ACTION_FORWARD_TO_DC"},
			{"displayText":"Alert (IncapRule)","val":"RULE_ACTION_ALERT"},
			{"displayText":"Block Request (IncapRule)","val":"RULE_ACTION_BLOCK"},
			{"displayText":"Block Session (IncapRule)","val":"RULE_ACTION_BLOCK_USER"},
			{"displayText":"Block Ip (IncapRule)","val":"RULE_ACTION_BLOCK_IP"},
			{"displayText":"Require Cookie Support (IncapRule)","val":"RULE_ACTION_RETRY"},
			{"displayText":"Require JavaScript Support (IncapRule)","val":"RULE_ACTION_INTRUSIVE_HTML"},
			{"displayText":"Require CAPCHA Support (IncapRule/ADR)","val":"RULE_ACTION_CAPTCHA"}
		]},
	"activation_mode":{"desc":"One of the following: off (security measures are disabled even if site is under a DDoS attack), auto (security measures will be activated automatically when the system suspects site is under a DDoS attack), on (security measures are enabled even if site is not under a DDoS attack). The syntax is as follows: api.threats.ddos.activation_mode.( e.g. for 'off', use 'api.threats.ddos.activation_mode.off' ).",
		"type":"list","values":["","api.threats.ddos.activation_mode.on","api.threats.ddos.activation_mode.off","api.threats.ddos.activation_mode.auto"]},
	"add_missing":{"desc":"Add cookie or header if it doesn't exist (Rewrite cookie rule only)",
		"type":"string","values":""},
	"aggressive_cache_duration":{"desc":"",
		"type":"string","values":""},
	"allow_all_users":{"desc":"",
		"type":"string","values":""},
	"always_cache_resource_duration":{"desc":"",
		"type":"string","values":""},
	"always_cache_resource_pattern":{"desc":"",
		"type":"string","values":""},
	"always_cache_resource_url":{"desc":"",
		"type":"string","values":""},
	"api_id":{"desc":"API authentication identifier",
		"type":"int","values":""},
	"api_key":{"desc":"API authentication identifier",
		"type":"string","values":""},
	"authentication_methods":{"desc":"Comma seperated list of allowed authentication methods sms | email | ga",
		"type":"string","values":"sms,email,ga"},
	"block_bad_bots":{"desc":"Whether or not to block bad bots. One of: true, false",
		"type":"list","values":["","true","false"]},
	"bps":{"desc":"Number of bits per second.",
		"type":"int","values":""},
	"bucket_name":{"desc":"S3 bucket name.",
		"type":"string","values":""},
	"cache_mode":{"desc":"disable | static_only | static_and_dynamic | aggressive : default Static_Only.",
		"type":"list","values":["static_only","disable","static_and_dynamic","aggressive"]},
	"cahce_headers":{"desc":"",
		"type":"string","values":""},
	"certificate":{"desc":"",
		"type":"string","values":""},
	"challenge_suspected_bots":{"desc":"Whether or not to send a challenge to clients that are suspected to be bad bots (CAPTCHA for example). One of: true, false",
		"type":"list","values":["","true","false"]},
	"clear_always_cache_rules":{"desc":"",
		"type":"string","values":""},
	"clear_cache_headers_rules":{"desc":"",
		"type":"string","values":""},
	"clear_never_cache_rules":{"desc":"",
		"type":"string","values":""},
	"client_app_types":{"desc":"",
		"type":"string","values":""},
	"client_apps":{"desc":"",
		"type":"string","values":""},
	"config_id":{"desc":"The Logs Collector configuration identifier",
		"type":"string","values":""},
	"connection_name":{"desc":"The connection to send a notification for. Enter the connection name as it appears in the Management Console’s Protection Settings page. For example, Test_GRE_Tunnel.",
		"type":"string","values":""},
	"content":{"desc":"The injected HTML snippet, Base64-encoded.",
		"type":"string","values":""},
	"continents":{"desc":"Continents by code",
		"type":"multi","values":["AF","AN","AS","EU","NA","OC","SA"]},
	"countries":{"desc":"Countries by code",
		"type":"multi","values":["AF","AX","AL","DZ","AS","AD","AO","AI","AQ","AG","AR","AM","AW","AU","AT","AZ","BS","BH","BD","BB","BY","BE","BZ","BJ","BM","BT","BO","BA","BW","BV","BR","VG","IO","BN","BG","BF","BI","KH","CM","CA","CV","KY","CF","TD","CL","CN","HK","MO","CX","CC","CO","KM","CG","CD","CK","CR","CI","HR","CU","CY","CZ","DK","DJ","DM","DO","EC","EG","SV","GQ","ER","EE","ET","FK","FO","FJ","FI","FR","GF","PF","TF","GA","GM","GE","DE","GH","GI","GR","GL","GD","GP","GU","GT","GG","GN","GW","GY","HT","HM","VA","HN","HU","IS","IN","ID","IR","IQ","IE","IM","IL","IT","JM","JP","JE","JO","KZ","KE","KI","KP","KR","KW","KG","LA","LV","LB","LS","LR","LY","LI","LT","LU","MK","MG","MW","MY","MV","ML","MT","MH","MQ","MR","MU","YT","MX","FM","MD","MC","MN","ME","MS","MA","MZ","MM","NA","NR","NP","NL","AN","NC","NZ","NI","NE","NG","NU","NF","MP","NO","OM","PK","PW","PS","PA","PG","PY","PE","PH","PN","PL","PT","PR","QA","RE","RO","RU","RW","BL","SH","KN","LC","MF","PM","VC","WS","SM","ST","SA","SN","RS","SC","SL","SG","SK","SI","SB","SO","ZA","GS","SS","ES","LK","SD","SR","SJ","SZ","SE","CH","SY","TW","TJ","TZ","TH","TL","TG","TK","TO","TT","TN","TR","TM","TC","TV","UG","UA","AE","GB","US","UM","UY","UZ","VU","VE","VN","VI","WF","EH","YE","ZM","ZW"]},
	"country":{"desc":"Country by code",
		"type":"list","values":["","AF","AX","AL","DZ","AS","AD","AO","AI","AQ","AG","AR","AM","AW","AU","AT","AZ","BS","BH","BD","BB","BY","BE","BZ","BJ","BM","BT","BO","BA","BW","BV","BR","VG","IO","BN","BG","BF","BI","KH","CM","CA","CV","KY","CF","TD","CL","CN","HK","MO","CX","CC","CO","KM","CG","CD","CK","CR","CI","HR","CU","CY","CZ","DK","DJ","DM","DO","EC","EG","SV","GQ","ER","EE","ET","FK","FO","FJ","FI","FR","GF","PF","TF","GA","GM","GE","DE","GH","GI","GR","GL","GD","GP","GU","GT","GG","GN","GW","GY","HT","HM","VA","HN","HU","IS","IN","ID","IR","IQ","IE","IM","IL","IT","JM","JP","JE","JO","KZ","KE","KI","KP","KR","KW","KG","LA","LV","LB","LS","LR","LY","LI","LT","LU","MK","MG","MW","MY","MV","ML","MT","MH","MQ","MR","MU","YT","MX","FM","MD","MC","MN","ME","MS","MA","MZ","MM","NA","NR","NP","NL","AN","NC","NZ","NI","NE","NG","NU","NF","MP","NO","OM","PK","PW","PS","PA","PG","PY","PE","PH","PN","PL","PT","PR","QA","RE","RO","RU","RW","BL","SH","KN","LC","MF","PM","VC","WS","SM","ST","SA","SN","RS","SC","SL","SG","SK","SI","SB","SO","ZA","GS","SS","ES","LK","SD","SR","SJ","SZ","SE","CH","SY","TW","TJ","TZ","TH","TL","TG","TK","TO","TT","TN","TR","TM","TC","TV","UG","UA","AE","GB","US","UM","UY","UZ","VU","VE","VN","VI","WF","EH","YE","ZM","ZW"]},
	"dc_id":{"desc":"Data Center ID",
		"type":"list","values":[]},
	"data_storage_region":{"desc":"The data region to use.",
		"type":"list","values":["APAC","EU","US","DEFAULT"]},
	"ddos_traffic_threshold":{"desc":"Consider site to be under DDoS if the request rate is above this threshold.",
		"type":"list","values":['',10, 20, 50, 100, 200, 500, 750, 1000, 2000, 3000, 4000, 5000]},
	"destination_account_id":{"desc":"The numeric identifier of the account which the site will be moved to.",
		"type":"int","values":""},
	"delete_content":{"desc":"The injected HTML snippet, Base64-encoded.",
		"type":"list","values":["","true","false"]},
	"delete_whitelist":{"desc":"An optional boolean parameter, in case it is set to 'true' and a whitelist id is sent, then the whitelist will be deleted",
		"type":"list","values":["","true"]},
	"destination_folder":{"desc":"The path to the directory on the SFTP server.",
		"type":"string","values":"true"},
	"displayName":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"domain":{"desc":"The domain name of the site. For example: www.example.com, hello.example.com, example.com",
		"type":"string","values":""},
	"dynamic_cache_duration":{"desc":"",
		"type":"string","values":""},
	"email":{"desc":"Email address. For example: brian@example.com",
		"type":"string","values":""},
	"enable":{"desc":"",
		"type":"string","values":""},
	"enabled":{"desc":"",
		"type":"list","values":["","true","false"]},
	"end":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"event_type":{"desc":"A comma separated list of specific event types. Any of: GRE_TUNNEL_UP,GRE_TUNNEL_DOWN, ORIGIN_CONNECTION_GRE_UP,ORIGIN_CONNECTION_GRE_DOWN,ORIGIN_CONNECTION_ECX_UP,ORIGIN_CONNECTION_ECX_DOWN,ORIGIN_CONNECTION_CROSS_CONNECT_UP,ORIGIN_CONNECTION_CROSS_CONNECT_DOWN,DDOS_START_IP_RANGE,DDOS_STOP_IP_RANGE,DDOS_QUIET_TIME_IP_RANGE,EXPORTER_NO_DATA, EXPORTER_BAD_DATA, EXPORTER_GOOD_DATA, MONITORING_CRITICAL_ATTACK, PROTECTED_IP_STATUS_UP, PROTECTED_IP_STATUS_DOWN, PER_IP_DDOS_START_IP_RANGE.",
		"type":"string","values":"GRE_TUNNEL_UP,GRE_TUNNEL_DOWN,ORIGIN_CONNECTION_GRE_UP,ORIGIN_CONNECTION_GRE_DOWN,ORIGIN_CONNECTION_ECX_UP,ORIGIN_CONNECTION_ECX_DOWN,ORIGIN_CONNECTION_CROSS_CONNECT_UP,ORIGIN_CONNECTION_CROSS_CONNECT_DOWN,DDOS_START_IP_RANGE,DDOS_STOP_IP_RANGE,DDOS_QUIET_TIME_IP_RANGE,EXPORTER_NO_DATA,EXPORTER_BAD_DATA,EXPORTER_GOOD_DATA,MONITORING_CRITICAL_ATTACK,PROTECTED_IP_STATUS_UP,PROTECTED_IP_STATUS_DOWN,PER_IP_DDOS_START_IP_RANGE"},
	"exporter_ip":{"desc":"The exporter IP to send a notification for. For example, 1.1.1.1. The exporter IP can be found in the Management Console’s Monitoring Settings page.",
		"type":"string","values":"1.1.1.1"},
	"filter":{"desc":"Rule will trigger only a request that matches this filter. Filter guidelines can be found here.",
		"type":"filter","values":[]},
	"force_ssl":{"desc":"This is a tmp desc",
		"type":"list","values":["","true","false"]},
	"format":{"desc":"",
		"type":"string","values":""},
	/*"from":{"desc":"Pattern to rewrite. RULE_ACTION_REWRITE_URL - Url to rewrite. RULE_ACTION_REWRITE_HEADER - Header value to rewrite. RULE_ACTION_REWRITE_COOKIE - Cookie value to rewrite.",
		"type":"listPair","values":[
			{"displayText":"Rewrite URL","val":"RULE_ACTION_REWRITE_URL"},
			{"displayText":"Rewrite Header","val":"RULE_ACTION_REWRITE_HEADER"},
			{"displayText":"Rewrite Cookie","val":"RULE_ACTION_REWRITE_COOKIE"}
		]},*/
	"from":{"desc":"Pattern to rewrite. RULE_ACTION_REWRITE_URL - Url to rewrite. RULE_ACTION_REWRITE_HEADER - Header value to rewrite. RULE_ACTION_REWRITE_COOKIE - Cookie value to rewrite.",
		"type":"string","values":""},
	"granularity":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"host":{"desc":"",
		"type":"string","values":""},
	"host_name":{"desc":"",
		"type":"string","values":""},
	"id_enabled":{"desc":"",
		"type":"string","values":""},
	"include_ad_rules":{"desc":"This is a tmp desc",
		"type":"list","values":["","Yes","No"]},
	"include_incap_rules":{"desc":"This is a tmp desc",
		"type":"list","values":["","Yes","No"]},
	"ip":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"ips":{"desc":"A comma seperated list of IPs or IP ranges, e.g: 192.168.1.1, 192.168.1.1-192.168.1.100 or 192.168.1.1/24",
		"type":"string","values":""},
	"ip_prefix":{"desc":"Specific Protected IP or IP&nbsp;range. For example, 1.1.1.0/24.",
		"type":"string","values":"1.1.1.0/24"},
	"ip_protection":{"desc":"The IP to send a notification for. For example, 1.1.1.1.",
		"type":"string","values":"1.1.1.0/24."},
	"is_content":{"desc":"",
		"type":"list","values":["","Yes"]},
	"is_email_verified":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"is_phone_verified":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"is_standby":{"desc":"",
		"type":"list","values":["","Yes"]},
	"is_test_mode":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"lb_algorithm":{"desc":"Data center load balancing algorithm. Possible values are:\rLB_LEAST_PENDING_REQUESTS - Server with least pending requests\rLB_LEAST_OPEN_CONNECTIONS = Server with least open connections\rLB_SOURCE_IP_HASH - Server by IP hash]\rRANDOM - Random server",
		"type":"list","values":["","LB_LEAST_PENDING_REQUESTS","LB_LEAST_OPEN_CONNECTIONS","LB_SOURCE_IP_HASH","RANDOM"]},
	"list_live_visits":{"desc":"This is a tmp desc",
		"type":"list","values":["","true","false"]},
	"location":{"desc":"The location of the injection inside the URL ('head' or 'body_end').",
		"type":"list","values":["","head","body_end"]},	
	"log_level":{"desc":"Available only for Enterprise Plan customers that purchased the Logs Integration SKU. (optional)",
		"type":"list","values":["default","none","full","security"]},
	"logs_account_id":{"desc":"Numeric identifier of the account that purchased the logs integration SKU and which collects the logs. If not specified, operation will be performed on the account identified by the authentication parameters.  Available only for Enterprise Plan customers that purchased the Logs Integration SKU. (optional)",
		"type":"int","values":""},
	"logs_collector_type":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"logs_config_new_status":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"max_events":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"name":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"never_cache_resource_url":{"desc":"",
		"type":"string","values":""},
	"never_cahce_resource_pattern":{"desc":"",
		"type":"string","values":""},
	"organization":{"desc":"The legal name of your organization. This should not be abbreviated or include suffixes such as Inc., Corp., or LLC. (optional)",
		"type":"string","values":""},
	"organization_unit":{"desc":"The division of your organization handling the certificate. For example, 'IT Department'. (optional)",
		"type":"string","values":""},
	"packet_type":{"desc":"Packet type. (UDP, TCP, DNS, DNS_RESPONSE, ICMP, SYN, FRAG, LARGE_SYN, NTP, NETFLOW, SSDP, GENERAL)",
		"type":"list","values":["","UDP","TCP","DNS","DNS_RESPONSE","ICMP","SYN","FRAG","LARGE_SYN","NTP","NETFLOW","SSDP","GENERAL"]},
	"page_num":{"desc":"The page to return starting from 0. Default: 0",
		"type":"int","values":"0"},
	"page_size":{"desc":"The number of objects to return in the response. Default: 50",
		"type":"int","values":"100"},
	"param":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"parameters":{"desc":"",
		"type":"string","values":""},
	"parent_id":{"desc":"The newly created account's parent id. If not specified, the invoking account will be assigned as the parent account. (optional)",
		"type":"int","values":""},
	"password":{"desc":"",
		"type":"string","values":""},
	"passphrase":{"desc":"",
		"type":"string","values":""},
	"phone":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"plan_id":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"pps":{"desc":"Number of packets per second.",
		"type":"int","values":""},
	"priority":{"desc":"",
		"type":"string","values":""},
	"private_key":{"desc":"",
		"type":"string","values":""},
	"protected_app":{"desc":"This is a tmp desc",
		"type":"list","values":["joomla","wordpress","phpBB"]},
	"protocol":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"public_key":{"desc":"The public key file(2048bit) in base64 format (without password protection)",
		"type":"string","values":""},
	"purge_pattern":{"desc":"This is a tmp desc",
		"type":"string","values":"^Resource_name$"},
	"quarantined_urls":{"desc":"A comma seperated list of encoded URLs to be kept in quarantine",
		"type":"string","values":""},
	"ref_id":{"desc":"Customer specific identifier for this operation. (optional)",
		"type":"string","values":""},
	"report":{"desc":"",
		"type":"string","values":""},
	"resource_pattern":{"desc":"",
		"type":"string","values":""},
	"resource_url":{"desc":"",
		"type":"string","values":""},
	"resp_format":{"desc":"This is a tmp desc",
		"type":"list","values":["json","apache","nginx","iptables","text"]},
	"response_code":{"desc":"This is a tmp desc",
		"type":"list","values":["",301, 302, 303, 307, 308]},
	"revision_id":{"desc":"",
		"type":"string","values":""},
	"rewrite_name":{"desc":"Name of cookie or header to rewrite. Applies only for RULE_ACTION_REWRITE_COOKIE and RULE_ACTION_REWRITE_HEADER",
		"type":"string","values":""},
	"rule_id":{"desc":"The id of the acl, e.g api.acl.blacklisted_ips:\r\n• api.acl.blacklisted_countries - Visitors from blacklisted countries/continents\r\n• api.acl.blacklisted_urls - Visitors from blacklisted URLs\r\n• api.acl.blacklisted_ips - Visitors from blacklisted IPs\r\n• api.acl.whitelisted_ips - Visitors from whitelisted IPs\n\r\n\rBlacklisted URLs Example:\r\nrule_id=api.acl.blacklisted_urls\r\nurls=%2Fadmin%2Fdashboard%2Fstats%3Fx%3D1%26y%3D2%23z%3D3,%2Fadmin\r\nurl_patterns=contains,equals\r\n\r\nBlacklisted Countries Example:\r\nrule_id=api.acl.blacklisted_countries\r\ncountries=CA,US\r\ncontinents=SA\r\n\r\nBlacklisted IPs Example:\r\nrule_id=api.acl.blacklisted_ips\r\nips=1.2.3.4,192.168.1.1-192.168.1.100,192.168.1.1/24\r\n\r\nWhitelisted IPs Example:\r\nrule_id=api.acl.whitelisted_ips\r\nips=1.2.3.4\r\n\r\nDelete the IPs ACL Example (send an empty list of IPs):\r\nrule_id=api.acl.blacklisted_ips\r\nips=\r\n",
		"type":"list","values":["","api.acl.blacklisted_countries","api.acl.blacklisted_ips","api.acl.blacklisted_urls","api.acl.whitelisted_ips","api.threats.backdoor","api.threats.bot_access_control","api.threats.cross_site_scripting","api.threats.ddos","api.threats.illegal_resource_access","api.threats.remote_file_inclusion","api.threats.sql_injection"]},
	"save_on_success":{"desc":"Save on success.",
		"type":"list","values":["","true","false"]},
	"secret_key":{"desc":"S3 secret key.",
		"type":"string","values":""},
	"security_rule_action":{"desc":"The action that should be taken when a threat is detected, for example: api.threats.action.block_ip. Different actions are allowed per different threats, e.g. backdoors may only be quarantined, ignored or trigger an alert. For possible values see below:\r\n\r\n• api.threats.action.disabled - Threat is not blocked, site owner is not notified.\r\n• api.threats.action.alert - Threat is not blocked, site owner is notified.\r\n• api.threats.action.block_request - Threat blocked by stopping the request, site owner is notified.\r\n• api.threats.action.block_user - Threat blocked by stopping the request. Additional requests by the client application will be automatically blocked for a duration of several minutes. Site owner is notified.\r\n• api.threats.action.block_ip - Threat blocked by stopping the request. Additional requests from the same IP addresses will be automatically blocked for a duration of several minutes. Site owner is notified.\r\n• api.threats.action.quarantine_url - Relevant only for Backdoor Protect. When detecting a backdoor, additional requests to the URL of the backdoor will be automatically blocked. Site owner is notified.",
		"type":"list","values":["","api.threats.action.disabled","api.threats.action.alert","api.threats.action.block_request","api.threats.action.block_user","api.threats.action.block_ip","api.threats.action.quarantine_url"]},
	"security":{"desc":"The security settings of the site",
		"type":"string","values":""},
	"send_lp_notifications":{"desc":"This is a tmp desc",
		"type":"list","values":["","true","false"]},
	"send_site_setup_emails":{"desc":"This is a tmp desc",
		"type":"list","values":["","true","false"]},
	"server_address":{"desc":"",
		"type":"string","values":""},
	"server_id":{"desc":"",
		"type":"string","values":""},
	"should_purge_all_site_resources":{"desc":"",
		"type":"string","values":""},
	"should_send_activation_email":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"site_id":{"desc":"Numeric identifier of the site to operate on.","desc":"This is a tmp desc",
		"type":"list","values":[]},
	"site_ip":{"desc":"This is a tmp desc",
		"type":"int","values":""},
	"sms_text":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"specific_users_list":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"start":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"state":{"desc":"The state/region where your organization is located. This should not be abbreviated.",
		"type":"string","values":""},
	"stats":{"desc":"This is a tmp desc",
		"type":"list","values":["visits_timeseries","hits_timeseries","bandwidth_timeseries","requests_geo_dist_summary","visits_dist_summary","caching","caching_timeseries","threats"]},
	"sub_account_name":{"desc":"The name of the sub account.",
		"type":"string","values":""},
	"support_all_tls_versions":{"desc":"This is a tmp desc",
		"type":"list","values":["","true","false"]},
	"tests":{"desc":"",
		"type":"string","values":""},
	"time_range":{"desc":"Time range to fetch data for. See the introduction of the API documentation for a detailed description ",
		"type":"list","values":["today","last_7_days","last_30_days","last_90_days","month_to_date","custom"]},
	/*"to":{"desc":"Pattern to change to. RULE_ACTION_REWRITE_URL - Url to change to. RULE_ACTION_REWRITE_HEADER - Header value to change to. RULE_ACTION_REWRITE_COOKIE - Cookie value to change to",
		"type":"listPair","values":[
			{"displayText":"Rewrite URL","val":"RULE_ACTION_REWRITE_URL"},
			{"displayText":"Rewrite Header","val":"RULE_ACTION_REWRITE_HEADER"},
			{"displayText":"Rewrite Cookie","val":"RULE_ACTION_REWRITE_COOKIE"}
		]},*/
	"to":{"desc":"Pattern to change to. RULE_ACTION_REWRITE_URL - Url to change to. RULE_ACTION_REWRITE_HEADER - Header value to change to. RULE_ACTION_REWRITE_COOKIE - Cookie value to change to",
		"type":"string","values":""},
	"traffic":{"desc":"Specific traffic. One of: Total, Passed, Blocked.",
		"type":"list","values":["","Total","Passed","Blocked"]},
	"type":{"desc":"The api key of the event type, such as audit.account_login.",
		"type":"string","values":""},
	"url":{"desc":"The URL where the content is injected.",
		"type":"string","values":""},
	"url_patterns":{"desc":"A comma seperated list of url patterns, one or multiple of: contains | equals | prefix | suffix | not_equals | not_contain | not_prefix | not_suffix. The patterns should be in accordance with the matching urls sent by the urls parameter.",
		"type":"string","values":"contains,equals,prefix,suffix,not_equals,not_contain,not_prefix,not_suffix"},
	"urls":{"desc":"This is a tmp desc",
		"type":"string","values":"/admin,index.php"},
	"user_agents":{"desc":"",
		"type":"string","values":""},
	"user_name":{"desc":"Username",
		"type":"string","values":""},
	"value":{"desc":"Value",
		"type":"string","values":""},
	"visit_id":{"desc":"This is a tmp desc",
		"type":"string","values":""},
	"whitelist_id":{"desc":"The id (an integer) of the whitelist to be set. This field is optional - in case no id is supplied, a new whitelist will be created",
		"type":"string","values":""}
};
//ip_prefix","traffic","traffic_type","pop"
var incapApiActions = {
	"Account Management":{
		"/api/prov/v1/account":["api_id","api_key","account_id"],
		"/api/prov/v1/accounts/add":["api_id","api_key","email","parent_id","user_name","plan_id","ref_id","account_name","log_level","logs_account_id"],
		"/api/prov/v1/accounts/audit":["api_id","api_key","account_id","time_range","start","end","type","page_size","page_num"],
		"/api/prov/v1/accounts/configure":["api_id","api_key","account_id","param","value"],
		"/api/prov/v1/accounts/data-privacy/set-region-default":["api_id","api_key","account_id","data_storage_region"],
		"/api/prov/v1/accounts/data-privacy/show":["api_id","api_key","account_id"],
		"/api/prov/v1/accounts/delete":["api_id","api_key","account_id"],
		"/api/prov/v1/accounts/gettoken":["api_id","api_key","account_id"],
		"/api/prov/v1/accounts/list":["api_id","api_key","account_id","page_size","page_num"],
		"/api/prov/v1/accounts/setlog":["api_id","api_key","account_id","log_level"],
		"/api/prov/v1/accounts/setAmazonSiemStorage":["api_id","api_key","account_id","bucket_name","access_key","secret_key"],
		"/api/prov/v1/accounts/setSftpSiemStorage":["api_id","api_key","account_id","host","user_name","password","destination_folder"],
		"/api/prov/v1/accounts/setDefaultSiemStorage":["api_id","api_key","account_id"],
		"/api/prov/v1/accounts/testS3Connection":["api_id","api_key","account_id","bucket_name","access_key","secret_key","save_on_success"],
		"/api/prov/v1/accounts/testSftpConnection":["api_id","api_key","account_id","host","user_name","password","destination_folder","save_on_success"],
		"/api/prov/v1/subaccounts/add":["api_id","api_key","sub_account_name","parent_id","ref_id","log_level","logs_account_id"],
		"/api/prov/v1/subaccounts/delete":["api_id","api_key","sub_account_id"],
		"/api/prov/v1/accounts/listSubAccounts":["api_id","api_key","account_id","page_size","page_num"]
	},
	//"email","organization","organization_unit","country","state","city"
	"Site Management":{
		"/api/prov/v1/caa/check-compliance":["api_id","api_key","site_id"],
		"/api/prov/v1/domain/emails":["api_id","api_key","domain"],
		"/api/prov/v1/sites/data-privacy/region-change":["api_id","api_key","site_id","data_storage_region"],
		"/api/prov/v1/sites/data-privacy/show":["api_id","api_key","site_id"],
		"/api/prov/v1/sites/add":["api_id","api_key","domain","account_id","ref_id","send_site_setup_emails","site_ip","force_ssl","log_level","logs_account_id"],
		"/api/prov/v1/sites/cache/purge":["api_id","api_key","site_id","purge_pattern"],
		"/api/prov/v1/sites/configure":["api_id","api_key","site_id","param","value"],
		"/api/prov/v1/sites/configure/acl":["api_id","api_key","site_id","rule_id","urls","url_patterns","countries","continents","ips"],
		"/api/prov/v1/sites/configure/htmlInjections":["api_id","api_key","site_id","url","url_pattern","location","content"],
		"/api/prov/v1/sites/configure/security":["api_id","api_key","site_id","rule_id","block_bad_bots","challenge_suspected_bots","activation_mode","security_rule_action","quarantined_urls","ddos_traffic_threshold"],
		"/api/prov/v1/sites/configure/whitelists":["api_id","api_key","site_id","rule_id","whitelist_id","delete_whitelist","urls","countries","continents","ips","client_app_types","client_apps","parameters","user_agents"],
		"/api/prov/v1/sites/customCertificate/csr":["api_id","api_key","site_id","email","organization","organization_unit","country","state","city"],
		"/api/prov/v1/sites/customCertificate/remove":["api_id","api_key","site_id"],
		"/api/prov/v1/sites/customCertificate/upload":["api_id","api_key","site_id","certificate","private_key","passphrase"],
		"/api/prov/v1/sites/dataCenters/add":["api_id","api_key","site_id","name","server_address","is_standby","is_content"],
		"/api/prov/v1/sites/dataCenters/delete":["api_id","api_key","dc_id"],
		"/api/prov/v1/sites/dataCenters/edit":["api_id","api_key","dc_id","name","is_standby","is_content"],
		"/api/prov/v1/sites/dataCenters/list":["api_id","api_key","site_id"],
		"/api/prov/v1/sites/dataCenters/servers/add":["api_id","api_key","dc_id","server_address","is_standby"],
		"/api/prov/v1/sites/dataCenters/servers/delete":["api_id","api_key","server_id"],
		"/api/prov/v1/sites/dataCenters/servers/edit":["api_id","api_key","server_id","server_address","is_enabled","is_standby"],
		"/api/prov/v1/sites/delete":["api_id","api_key","site_id"],
		"/api/prov/v1/sites/hostname/purge":["api_id","api_key","host_name"],
		"/api/prov/v1/sites/htmlinjections":["api_id","api_key","site_id"],
		"/api/prov/v1/sites/incapRules/account/list":["api_id","api_key","account_id","include_ad_rules","include_incap_rules"],
		"/api/prov/v1/sites/incapRules/add":["api_id","api_key","site_id","name","action","filter","response_code","protocol","add_missing","from","to","rewrite_name","dc_id","is_test_mode","lb_algorithm"],
		"/api/prov/v1/sites/incapRules/delete":["api_id","api_key","rule_id"],
		"/api/prov/v1/sites/incapRules/edit":["api_id","api_key","rule_id","name","action","filter","response_code","protocol","add_missing","from","to","rewrite_name","dc_id","is_test_mode","lb_algorithm"],
		"/api/prov/v1/sites/incapRules/enableDisable":["api_id","api_key","rule_id","enable"],
		"/api/prov/v1/sites/incapRules/list":["api_id","api_key","site_id","include_ad_rules","include_incap_rules"],
		"/api/prov/v1/sites/incapRules/priority/set":["api_id","api_key","rule_id","priority"],
		"/api/prov/v1/sites/incapRules/revert":["api_id","api_key","site_id","rule_id","revision_id"],
		"/api/prov/v1/sites/incapRules/revisions":["api_id","api_key","site_id","rule_id"],
		"/api/prov/v1/sites/list":["api_id","api_key","account_id","page_size","page_num"],
		"/api/prov/v1/sites/moveSite":["api_id","api_key","site_id","destination_account_id"],
		"/api/prov/v1/sites/performance/advanced":["api_id","api_key","site_id","param","value"],
		"/api/prov/v1/sites/performance/cache-mode":["api_id","api_key","site_id","cache_mode","dynamic_cache_duration","aggressive_cache_duration"],
		"/api/prov/v1/sites/performance/caching-rules":["api_id","api_key","site_id","always_cache_resource_url","always_cache_resource_pattern","always_cache_resource_duration","never_cache_resource_url","never_cahce_resource_pattern","cahce_headers","clear_always_cache_rules","clear_never_cache_rules","clear_cache_headers_rules"],
		"/api/prov/v1/sites/performance/purge":["api_id","api_key","site_id","resource_url","resource_pattern","should_purge_all_site_resources"],
		"/api/prov/v1/sites/report":["api_id","api_key","site_id","report","format","time_range","start","end"],
		"/api/prov/v1/sites/setlog":["api_id","api_key","site_id","log_level"],
		"/api/prov/v1/sites/status":["api_id","api_key","site_id","tests"],
		"/api/prov/v1/sites/tls":["api_id","api_key","site_id","support_all_tls_versions"],
		"/api/prov/v1/sites/xray/get-link":["api_id","api_key","site_id"]
	},
	"Traffic Statistics and Details":{
		"/api/logscollector/change/status":["api_id","api_key","config_id","logs_config_new_status"],
		"/api/logscollector/upload/publickey":["api_id","api_key","config_id","public_key"],
		"/api/stats/v1":["api_id","api_key","account_id","time_range","start","end","site_id","stats","granularity"],
		"/api/visits/v1":["api_id","api_key","site_id","time_range","start","end","page_size","page_num","security","country","ip","visit_id","list_live_visits"],
		"/api/v1/infra/stats":["api_id","api_key","account_id","ip_prefix","traffic","traffic_type","pop","start","end"],
		"/api/v1/infra/events":["api_id","api_key","account_id","event_type","ip_prefix","page_size","page_num","start","end"]
	},
	"Login Protect":{
		"/api/prov/v1/sites/lp/add-user":["api_id","api_key","account_id","email","name","phone","is_email_verified","is_phone_verified","should_send_activation_email"],
		"/api/prov/v1/sites/lp/configure-app":["api_id","api_key","site_id","protected_app"],
		"/api/prov/v1/sites/lp/configure":["api_id","api_key","site_id","enabled","specific_users_list","send_lp_notifications","allow_all_users","authentication_methods","urls","url_patterns"],
		"/api/prov/v1/sites/lp/edit-user":["api_id","api_key","account_id","email","name","phone","is_email_verified","is_phone_verified","should_send_activation_email"],
		"/api/prov/v1/sites/lp/remove":["api_id","api_key","account_id","email"],
		"/api/prov/v1/sites/lp/send-sms":["api_id","api_key","account_id","email","sms_text"],
		"/api/prov/v1/sites/lp/users":["api_id","api_key","account_id"]
	},
	"Infrastructure Protection":{
		"/api/v1/infra-protect/test-alerts/ddos/start":["api_id","api_key","ip_prefix","bps","pps"],
		"/api/v1/infra-protect/test-alerts/ddos/stop":["api_id","api_key","ip_prefix","bps","pps"],
		"/api/v1/infra-protect/test-alerts/connection/up":["api_id","api_key","connection_name"],
		"/api/v1/infra-protect/test-alerts/connection/down":["api_id","api_key","connection_name"],
		"/api/v1/infra-protect/test-alerts/ip-protection-status/down":["api_id","api_key","ip_protection"],
		"/api/v1/infra-protect/test-alerts/ip-protection-status/up":["api_id","api_key","ip_protection"],
		"/api/v1/infra-protect/test-alerts/monitoring/attack-start":["api_id","api_key","ip_prefix","bps","pps","packet_type"],
		"/api/v1/infra-protect/test-alerts/monitoring/bad-data":["api_id","api_key","exporter_ip"],
		"/api/v1/infra-protect/test-alerts/monitoring/start":["api_id","api_key","exporter_ip"],
		"/api/v1/infra-protect/test-alerts/monitoring/stop":["api_id","api_key","exporter_ip"]
	},
	"Integration":{
		"/api/integration/v1/clapps":["api_id","api_key"],
		"/api/integration/v1/geo":["api_id","api_key"],
		"/api/integration/v1/ips":["resp_format"],
		"/api/integration/v1/texts":["api_id","api_key"]
	},
	"Custom":{
		"/api/v1/sites/settings/customRules/showOptimizedMultiValues":["api_id","api_key","extSiteId"],
		"/api/v1/sites/settings/customRules/validateCustomRule":["api_id","api_key","extSiteId"],
		"/api/v1/sites/settings/customRules/init":["api_id","api_key","extSiteId"],
		"/api/v1/sites/settings/customRules/validateCustomRule":["api_id","api_key","extSiteId","filter"],
		"/sites/rules/redirect/dismiss":["api_id","api_key","extSiteId"]
	}
}

var incapSampleRules = {
	"Incap Rules":[
		{"enabled":"true","name":"Chrome Require JS","action":"RULE_ACTION_INTRUSIVE_HTML","filter":" ClientId == 3"},
		{"enabled":"true","name":"Block Vulnerability Scanners","action":"RULE_ACTION_BLOCK","filter":" ClientType == VulnerabilityScanner | ClientType == DDoSBot"},
		{"enabled":"true","name":"Demo_test","action":"RULE_ACTION_INTRUSIVE_HTML","filter":"HeaderExists != \"User-Agent\" & URL == \"/checkout.jsp\" & ( CountryCode == RU | CountryCode == CN )"},
		{"enabled":"true","name":"Registration Validation","action":"RULE_ACTION_CAPTCHA","filter":" URL contains \"register.jsp\" & ClientType != Browser"},
		{"enabled":"false","name":"Dev Access","action":"RULE_ACTION_ALERT","filter":" ClientIP != 73.193.83.231 | ClientType != SearchBot"}
	],
	"Redirect Rules":[
		{"to":"https://www.sprvda.com$2","enabled":"true","priority":"27","response_code":"302","name":"Redirect to HTTPS & www","action":"RULE_ACTION_REDIRECT","from":"*://sprvda.com*","filter":""},
		{"to":"$scheme","enabled":"true","priority":"10","name":"Add X-Forwarded-Proto Header","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":"","rewrite_name":"X-Forwarded-Proto"},
		{"to":"!browser","enabled":"true","priority":"10","name":"Client Type != Browser","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":" ClientType != Browser","rewrite_name":"ClientId"},
		{"to":"$latitude","enabled":"true","priority":"10","name":"Geo Data Enrichment - Latitude","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":"","rewrite_name":"Incap-Geo-Latitude"},
		{"to":"$longitude","enabled":"true","priority":"10","name":"Geo Data Enrichment - Longitude","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":"","rewrite_name":"Incap-Geo-Longitude"},
		{"to":"$city","enabled":"true","priority":"10","name":"Geo Data Enrichment - City","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":"","rewrite_name":"Incap-Geo-City"},
		{"to":"Browser","enabled":"true","priority":"10","name":"Incap-Client-Type = Browser","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":" ClientType == Browser","rewrite_name":"Incap-Client-Type"},
		{"to":"ClickBot","enabled":"true","priority":"10","name":"Incap-Client-Type = ClickBot","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":" ClientType == ClickBot","rewrite_name":"Incap-Client-Type"},
		{"to":"CommentSpamBot","enabled":"true","priority":"10","name":"Incap-Client-Type CommentSpamBot","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":" ClientType == CommentSpamBot","rewrite_name":"Incap-Client-Type"},
		{"to":"Unknown","enabled":"true","priority":"10","name":"Incap-Client-Type = Unknown","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":" ClientType == Unknown","rewrite_name":"Incap-Client-Type"},
		{"to":"HackingTool","enabled":"true","priority":"11","name":"Incap-Client-Type = HackingTool","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":" ClientType == HackingTool","rewrite_name":"Incap-Client-Type"},
		{"to":"MaskingProxy","enabled":"true","priority":"11","name":"Incap-Client-Type = MaskingProxy","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":" ClientType == MaskingProxy","rewrite_name":"Incap-Client-Type"},
		{"to":"VulnerabilityScanner","enabled":"true","priority":"12","name":"Incap-Client-Type = VulnerabilityScanner","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":" ClientType == VulnerabilityScanner","rewrite_name":"Incap-Client-Type"},
		{"to":"PhantomJS","enabled":"true","priority":"13","name":"Incap-Client-ID = PhantomJS","action":"RULE_ACTION_REWRITE_HEADER","from":"","allow_caching":"false","filter":" ClientId == 417","rewrite_name":"Incap-Client-ID"}
	],
	"Forward Rules":[
		{"enabled":"false","priority":"33","name":"Forward Beta Customers to New DC","dc_id":"1121887","action":"RULE_ACTION_FORWARD_TO_DC","allow_caching":"false","filter":" ClientIP == 73.193.83.231"},
		{"enabled":"false","priority":"33","name":"Forward Search Crawler Traffic to SEO Origin","dc_id":"1121887","action":"RULE_ACTION_FORWARD_TO_DC","allow_caching":"false","filter":" ClientType == Crawler"}
	]
}

